version: 2.1
jobs:
  compile-and-test:
    docker:
      - image: circleci/elixir:1.10.0
        environment:
          MIX_ENV: test
          PGHOST: localhost
          PGUSERNAME: postgres
          RABBITMQ_CONNECTION_URL: amqp://guest:guest@localhost:5672
          RABBITMQ_API_URL: http://guest:guest@localhost:15672/api/
      - image: circleci/postgres:9.6-alpine
      - image: rabbitmq:3.8.9-management-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: ./bin/setup circleci
      - save_cache:
          key: v2-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - "deps"
            - "_build"
      - run:
          name: Wait for postgresql
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Wait for rabbitmq
          command: dockerize -wait tcp://guest:guest@localhost:15672 -timeout 1m
      - run: ./bin/ci
      - store_test_results:
          path: _build/test/lib/railway_ipc
workflows:
  build:
    jobs:
      - compile-and-test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - compile-and-test
